### ISSUE TITLE
Stripe/stripe-php released 7.0.1 version, please update composer.json requirements

### ISSUE THREAD

**Issue by diimpp** [lolmx/Stripe#2]

**Comment by lolmx** [comment]
I'll do that in the next hour 👍

**Comment by lolmx** [comment]
Done in #3, i wait for travis and i'll release 1.6.1

**Comment by lolmx** [comment]
Here it is, new version [1.6.1](https://github.com/lolmx/Stripe/releases/tag/1.6.1) :)

**Comment by diimpp** [comment]
Thank you!
